/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainCreationsIndexRouteImport } from './routes/(main)/creations/index'
import { Route as mainBlogsIndexRouteImport } from './routes/(main)/blogs/index'
import { Route as mainAchievementsIndexRouteImport } from './routes/(main)/achievements/index'
import { Route as mainAboutIndexRouteImport } from './routes/(main)/about/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainCreationsIndexRoute = mainCreationsIndexRouteImport.update({
  id: '/creations/',
  path: '/creations/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBlogsIndexRoute = mainBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAchievementsIndexRoute = mainAchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutIndexRoute = mainAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/about/': typeof mainAboutIndexRoute
  '/achievements/': typeof mainAchievementsIndexRoute
  '/blogs/': typeof mainBlogsIndexRoute
  '/creations/': typeof mainCreationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/about': typeof mainAboutIndexRoute
  '/achievements': typeof mainAchievementsIndexRoute
  '/blogs': typeof mainBlogsIndexRoute
  '/creations': typeof mainCreationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(main)/about/': typeof mainAboutIndexRoute
  '/(main)/achievements/': typeof mainAchievementsIndexRoute
  '/(main)/blogs/': typeof mainBlogsIndexRoute
  '/(main)/creations/': typeof mainCreationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/'
    | '/sign-up/'
    | '/about/'
    | '/achievements/'
    | '/blogs/'
    | '/creations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/achievements'
    | '/blogs'
    | '/creations'
  id:
    | '__root__'
    | '/(auth)'
    | '/(main)'
    | '/(main)/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(main)/about/'
    | '/(main)/achievements/'
    | '/(main)/blogs/'
    | '/(main)/creations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/creations/': {
      id: '/(main)/creations/'
      path: '/creations'
      fullPath: '/creations/'
      preLoaderRoute: typeof mainCreationsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/blogs/': {
      id: '/(main)/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof mainBlogsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/achievements/': {
      id: '/(main)/achievements/'
      path: '/achievements'
      fullPath: '/achievements/'
      preLoaderRoute: typeof mainAchievementsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about/': {
      id: '/(main)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof mainAboutIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainAboutIndexRoute: typeof mainAboutIndexRoute
  mainAchievementsIndexRoute: typeof mainAchievementsIndexRoute
  mainBlogsIndexRoute: typeof mainBlogsIndexRoute
  mainCreationsIndexRoute: typeof mainCreationsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainAboutIndexRoute: mainAboutIndexRoute,
  mainAchievementsIndexRoute: mainAchievementsIndexRoute,
  mainBlogsIndexRoute: mainBlogsIndexRoute,
  mainCreationsIndexRoute: mainCreationsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
